const DEFAULT_NUMBER_OF_ELEMENTS_IN_THE_RESPONSE = 100;
const MAX_NUMBER_OF_ELEMENTS_IN_THE_RESPONSE = 2500;

module.exports = {
  DEFAULT_NUMBER_OF_ELEMENTS_IN_THE_RESPONSE,
  MAX_NUMBER_OF_ELEMENTS_IN_THE_RESPONSE,
};
